import type { Metadata } from "next";
import "./globals.css";
import HeaderLogged from "@/component/header/HeaderLogged";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <HeaderLogged/>
      {children}
      </body>
    </html>
  );
}